version: '3'
services:
  flask:
    container_name: flask
    build: .
    command: python -u main.py
    ports:
      - 3000:3000
    links:
      - redis 

  redis:
    image : redis:latest
    container_name: redisdata
    ports:
      - 6379:80